environment:
    global:
        # Your package name
        PACKAGE: "EasyClangComplete"
    matrix:
        - SUBLIME_TEXT_VERSION : "3"
          PCINSTALL: true

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    - ps: if (${env:PCINSTALL} -eq $true) { .\appveyor.ps1 "install_package_control" -verbose }
    # install Package Control
    # - ps: .\appveyor.ps1 "install_package_control" -verbose
    - "pip install --upgrade pep8"
    - "pip install --upgrade pep257"
    - "pip install --upgrade pycodestyle"

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose
